### ISSUE TITLE
Unexpected crash when used with Trello

### ISSUE THREAD

**Issue by imanhpr** [MahdiAghaei1/rtlit#3]
Hello dear Mehdi. when I was working with Rtlit suddenly I found a bug in the Trello.
Furthermore, you can use the procedure below to reproduce it.
Step to reproduce:

1. Go to https://trello.com when RTLIT is installed on Chrome
2. Open a new card and put some RTL text in the description or comments
3. Save by quitting the card and the browser tab crashes

*NOTE:* Even when Trello is on the blacklist, it's gonna crash

**Comment by epicmet** [comment]
Thank you Iman, I'll look into it.
